matrix:
  include:
    - language: scala
      scala: 2.12.3
      script: sbt clean "test-only *BuffersTest *ExtractorTests *HorribleTests *LanguageTests *LongInputTests *InjectorsTest  *APITests"


    - language: java
      jdk: oraclejdk8
      script: sbt clean "test-only *BuilderTest *ExtractorTest"